export interface Records {
    id: string;
    idTracking: string;
    status: string;
    customer: string;
    wareHouseTQ: string;
    wareHouseVN: string;
    information: string;
    note: string;
    partner: string;
    time: string;
}


const records: Records[] = [
    {
        id: 'DPUS10082300002',
        idTracking:"H1106231513",
        status: "status",
        customer: "Customer 1",
        wareHouseTQ: "Kho TQ",
        wareHouseVN: "Kho VN",
        information: "Thoong tin",
        note: "Ghi chu",
        partner: "Hanoi SJC",
        time: "10/08/2023 13:30:51",
    },
    {
        id: 'DPUS2',
        idTracking:"H1102",
        status: "status",
        customer: "Customer 2",
        wareHouseTQ: "Kho TQ",
        wareHouseVN: "Kho VN",
        information: "Thoong tin",
        note: "Ghi chu",
        partner: "Hanoi SJC",
        time: "10/08/2023 13:30:51",
    },
    {
        id: 'DPUS3',
        idTracking:"H1103",
        status: "status",
        customer: "Customer 3",
        wareHouseTQ: "Kho TQ",
        wareHouseVN: "Kho VN",
        information: "Thoong tin",
        note: "Ghi chu",
        partner: "Hanoi SJC",
        time: "10/08/2023 13:30:51",
    },
    {
        id: 'DPUS4',
        idTracking:"H1104",
        status: "status",
        customer: "Customer 4",
        wareHouseTQ: "Kho TQ",
        wareHouseVN: "Kho VN",
        information: "Thoong tin",
        note: "Ghi chu",
        partner: "Hanoi SJC",
        time: "10/08/2023 13:30:51",
    },
    {
        id: 'DPUS5',
        idTracking:"H1105",
        status: "status",
        customer: "Customer 5",
        wareHouseTQ: "Kho TQ",
        wareHouseVN: "Kho VN",
        information: "Thoong tin",
        note: "Ghi chu",
        partner: "Hanoi SJC",
        time: "10/08/2023 13:30:51",
    },
    {
        id: 'DPUS6',
        idTracking:"H1106",
        status: "status",
        customer: "Customer 6",
        wareHouseTQ: "Kho TQ",
        wareHouseVN: "Kho VN",
        information: "Thoong tin",
        note: "Ghi chu",
        partner: "Hanoi SJC",
        time: "10/08/2023 13:30:51",
    },
    {
        id: 'DPUS7',
        idTracking:"H1107",
        status: "status",
        customer: "Customer 7",
        wareHouseTQ: "Kho TQ",
        wareHouseVN: "Kho VN",
        information: "Thoong tin",
        note: "Ghi chu",
        partner: "Hanoi SJC",
        time: "10/08/2023 13:30:51",
    },
    {
        id: 'DPUS8',
        idTracking:"H1108",
        status: "status",
        customer: "Customer 8",
        wareHouseTQ: "Kho TQ",
        wareHouseVN: "Kho VN",
        information: "Thoong tin",
        note: "Ghi chu",
        partner: "Hanoi SJC",
        time: "10/08/2023 13:30:51",
    },
    {
        id: 'DPUS9',
        idTracking:"H1109",
        status: "status",
        customer: "Customer 9",
        wareHouseTQ: "Kho TQ",
        wareHouseVN: "Kho VN",
        information: "Thoong tin",
        note: "Ghi chu",
        partner: "Hanoi SJC",
        time: "10/08/2023 13:30:51",
    },
    {
        id: 'DPUS10',
        idTracking:"H11010",
        status: "status",
        customer: "Customer 10",
        wareHouseTQ: "Kho TQ",
        wareHouseVN: "Kho VN",
        information: "Thoong tin",
        note: "Ghi chu",
        partner: "Hanoi SJC",
        time: "10/08/2023 13:30:51",
    },
   
];

const recordsDaNhapKho: Records[] = [
    {
        id: 'DaNhapKho',
        idTracking:"H1106231513",
        status: "status",
        customer: "Customer 1",
        wareHouseTQ: "Kho TQ",
        wareHouseVN: "Kho VN",
        information: "Thoong tin",
        note: "Ghi chu",
        partner: "Hanoi SJC",
        time: "10/08/2023 13:30:51",
    },
    {
        id: 'DPUS2',
        idTracking:"H1102",
        status: "status",
        customer: "Customer 2",
        wareHouseTQ: "Kho TQ",
        wareHouseVN: "Kho VN",
        information: "Thoong tin",
        note: "Ghi chu",
        partner: "Hanoi SJC",
        time: "10/08/2023 13:30:51",
    },
    {
        id: 'DPUS3',
        idTracking:"H1103",
        status: "status",
        customer: "Customer 3",
        wareHouseTQ: "Kho TQ",
        wareHouseVN: "Kho VN",
        information: "Thoong tin",
        note: "Ghi chu",
        partner: "Hanoi SJC",
        time: "10/08/2023 13:30:51",
    },
    {
        id: 'DPUS4',
        idTracking:"H1104",
        status: "status",
        customer: "Customer 4",
        wareHouseTQ: "Kho TQ",
        wareHouseVN: "Kho VN",
        information: "Thoong tin",
        note: "Ghi chu",
        partner: "Hanoi SJC",
        time: "10/08/2023 13:30:51",
    },
    {
        id: 'DPUS5',
        idTracking:"H1105",
        status: "status",
        customer: "Customer 5",
        wareHouseTQ: "Kho TQ",
        wareHouseVN: "Kho VN",
        information: "Thoong tin",
        note: "Ghi chu",
        partner: "Hanoi SJC",
        time: "10/08/2023 13:30:51",
    },
    {
        id: 'DPUS6',
        idTracking:"H1106",
        status: "status",
        customer: "Customer 6",
        wareHouseTQ: "Kho TQ",
        wareHouseVN: "Kho VN",
        information: "Thoong tin",
        note: "Ghi chu",
        partner: "Hanoi SJC",
        time: "10/08/2023 13:30:51",
    },
    {
        id: 'DPUS7',
        idTracking:"H1107",
        status: "status",
        customer: "Customer 7",
        wareHouseTQ: "Kho TQ",
        wareHouseVN: "Kho VN",
        information: "Thoong tin",
        note: "Ghi chu",
        partner: "Hanoi SJC",
        time: "10/08/2023 13:30:51",
    },
    {
        id: 'DPUS8',
        idTracking:"H1108",
        status: "status",
        customer: "Customer 8",
        wareHouseTQ: "Kho TQ",
        wareHouseVN: "Kho VN",
        information: "Thoong tin",
        note: "Ghi chu",
        partner: "Hanoi SJC",
        time: "10/08/2023 13:30:51",
    },
    {
        id: 'DPUS9',
        idTracking:"H1109",
        status: "status",
        customer: "Customer 9",
        wareHouseTQ: "Kho TQ",
        wareHouseVN: "Kho VN",
        information: "Thoong tin",
        note: "Ghi chu",
        partner: "Hanoi SJC",
        time: "10/08/2023 13:30:51",
    },
    {
        id: 'DPUS10',
        idTracking:"H11010",
        status: "status",
        customer: "Customer 10",
        wareHouseTQ: "Kho TQ",
        wareHouseVN: "Kho VN",
        information: "Thoong tin",
        note: "Ghi chu",
        partner: "Hanoi SJC",
        time: "10/08/2023 13:30:51",
    },
   
];

export { records,recordsDaNhapKho};
